# Generated by Django 4.2.16 on 2024-11-16 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_karute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='karute',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='karute',
            name='records',
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('karute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='main.karute')),
            ],
        ),
    ]
