# Generated by Django 4.2.16 on 2024-11-17 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_karute_created_date_remove_karute_records_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
